package com.ery.hadoop.hq.ws;
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ery.hadoop.hq.ws.client.MetaWsClient;
import com.ery.hadoop.hq.ws.client.MetaWsClientProxy;
import com.ery.hadoop.hq.ws.utils.MetaWsDataUtil;
import com.ery.hadoop.hq.ws.utils.WsRequest;
/**
 * This class was generated by Apache CXF 2.5.2 2012-10-26T17:46:20.734+08:00
 * Generated source version: 2.5.2
 */
public final class ClientInsertWS {

//http://localhost:8080/HadoopWebClient/hq.do?USERID=test_user&PASSWD=111111&QUERY_RULE_ID=3020&START_KEY=a&END_KEY=z&CURRENT_PAGE=1&PAGE_SIZE=20
	public static void main(String[] args) throws Exception {
	//  ��ʼ�ͻ��ˣ�ϵͳ����ʱ����һ�Σ�
		MetaWsClient.setAddress("http://133.64.92.239:8003/HadoopWebClient/WS/MetaWs?wsdl");
		MetaWsClient.setUsername("tfjuser");
		MetaWsClient.setPassword("tfjuser");

		MetaWsClient.init();
		MetaWsClientProxy proxy = MetaWsClient.getClientProxy();
		HashMap<String, Object> map  = new HashMap<String, Object>();
		map.put("SOURCE_ID",1);
		map.put("HT_NAME","WS_Test");
		List<Map> values=new ArrayList<Map>();
		
		HashMap<String, String> value = new HashMap<String, String>();
		values.add(value);
		value.put("ROWID","add");
		value.put("ca","ca");
		value.put("CB","cb");
		value.put("ea","ea");
		value.put("eb,ec","eb^ec");//合并字段 
		map.put("ITEM_DATA",MetaWsDataUtil.toJSON(values));
		
		WsRequest req = new WsRequest();
		req.setRuleCode("hbase04");
		req.setSimpleMap(map);
		System.out.println(MetaWsDataUtil.toJSON(MetaWsDataUtil.toJSON(req)));
		Map<?, ?> obj =  proxy.executeBySimpleMap("hbase04", Map.class, map);// ���ȡ��ָ����Ϣ
		System.out.println(MetaWsDataUtil.toJSON(obj));
		System.exit(0);
	}
}