package com.ery.hadoop.hq.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2 2012-10-26T17:46:20.921+08:00 Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://app.ws.hq.hadoop.ery.com/", name = "MetaWebServicePortType")
@XmlSeeAlso({ ObjectFactory.class })
public interface MetaWebServicePortType {

	@WebResult(name = "return", targetNamespace = "http://app.ws.hq.hadoop.ery.com/")
	@RequestWrapper(localName = "doGet", targetNamespace = "http://app.ws.hq.hadoop.ery.com/", className = "com.ery.hadoop.hq.ws.client.DoGet")
	@WebMethod
	@ResponseWrapper(localName = "doGetResponse", targetNamespace = "http://app.ws.hq.hadoop.ery.com/", className = "com.ery.hadoop.hq.ws.client.DoGetResponse")
	public java.lang.String doGet(
			@WebParam(name = "jsonStr", targetNamespace = "http://app.ws.hq.hadoop.ery.com/") java.lang.String jsonStr);

	@WebResult(name = "return", targetNamespace = "http://app.ws.hq.hadoop.ery.com/")
	@RequestWrapper(localName = "getAvailableWS", targetNamespace = "http://app.ws.hq.hadoop.ery.com/", className = "com.ery.hadoop.hq.ws.client.GetAvailableWS")
	@WebMethod
	@ResponseWrapper(localName = "getAvailableWSResponse", targetNamespace = "http://app.ws.hq.hadoop.ery.com/", className = "com.ery.hadoop.hq.ws.client.GetAvailableWSResponse")
	public java.lang.String getAvailableWS();
}
