package com.ery.hadoop.hq.ws.client.test;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ery.hadoop.hq.ws.client.MetaWsClient;
import com.ery.hadoop.hq.ws.client.MetaWsClientProxy;
import com.ery.hadoop.hq.ws.utils.MetaWsDataUtil;

/**
 * This class was generated by Apache CXF 2.5.2 2012-10-26T17:46:20.734+08:00 Generated source version: 2.5.2
 * 
 */
public final class TestClient {

	public static final int QUERY_PAGE = 1; // 分页查询

	public static void main(String[] args) throws Exception {

		// 初始客户端（系统启动时调用一次）
		MetaWsClient.setAddress("http://127.0.0.1:8080/HadoopWebClient");
		MetaWsClient.setUsername("test_user");
		MetaWsClient.setPassword("111111");
		MetaWsClient.init();// 初始，仅需调用一次

		// requestWS();
		requestQueryWS();
		// requestModifyWS();
		// requestDeleteWS();
	}

	private static void requestDeleteWS() {
		int type = 0;// 查询类型 0：分页查询

		// 需要执行WS请求时，先获取代理对象
		MetaWsClientProxy proxy = MetaWsClient.getClientProxy();
		HashMap<String, Object> param = new HashMap<String, Object>();
		param.put("USERID", "test_user");
		param.put("PASSWD", "111111");
		param.put("HT_NAME", "HbaseDcc_test");
		param.put("SOURCE_ID", "1060");

		List<String> lst = new ArrayList<String>();
		lst.add("13301278206-2013/07/30 15:56:57");
		param.put("ITEM_DATA", MetaWsDataUtil.toJSON(lst));

		// 请求数据
		Map<?, ?> obj = proxy.executeBySimpleMap("hbase05", Map.class, param);
		System.out.println(MetaWsDataUtil.toJSON(obj));
		System.exit(0);
	}

	private static void requestModifyWS() {
		int type = 0;// 查询类型 0：分页查询

		// 需要执行WS请求时，先获取代理对象
		MetaWsClientProxy proxy = MetaWsClient.getClientProxy();
		HashMap<String, Object> param = new HashMap<String, Object>();
		param.put("USERID", "test_user");
		param.put("PASSWD", "111111");
		param.put("HT_NAME", "HbaseDcc_test");
		param.put("SOURCE_ID", "1060");

		List<HashMap<String, Object>> lst = new ArrayList<HashMap<String, Object>>();
		HashMap<String, Object> itemparam = new HashMap<String, Object>();
		itemparam.put("ROWID", "13301278206-2013/07/30 15:56:57");
		itemparam.put("MDN", "13301278205");
		itemparam.put("RECVBYTE", "51");
		itemparam.put("SENDBYTE", "60");
		lst.add(itemparam);
		param.put("ITEM_DATA", MetaWsDataUtil.toJSON(lst));

		// 请求数据
		Map<?, ?> obj = proxy.executeBySimpleMap("hbase04", Map.class, param);
		System.out.println(MetaWsDataUtil.toJSON(obj));
		System.exit(0);
	}

	private static void requestQueryWS() {
		int type = 0;// 查询类型 0：分页查询

		// 需要执行WS请求时，先获取代理对象
		MetaWsClientProxy proxy = MetaWsClient.getClientProxy();
		HashMap<String, Object> param = new HashMap<String, Object>();
		param.put("USERID", "test_user");
		param.put("PASSWD", "111111");
		param.put("HT_NAME", "HbaseDcc_test");
		param.put("SOURCE_ID", "1060");
		param.put("START_KEY", "15388206897-2013/07/30 15:53:35");
		param.put("END_KEY", "15388260273-2013/07/30 15:56:04");
		param.put("COUNT", "20");

		// 请求数据
		Map<?, ?> obj = proxy.executeBySimpleMap("hbase02", Map.class, param);
		System.out.println(MetaWsDataUtil.toJSON(obj));
		System.exit(0);
	}

	private static void requestWS() {
		int type = 0;// 查询类型 0：分页查询

		// 需要执行WS请求时，先获取代理对象
		MetaWsClientProxy proxy = MetaWsClient.getClientProxy();
		HashMap<String, Object> param = new HashMap<String, Object>();
		param.put("USERID", "wanghao");
		param.put("PASSWD", "123456");
		param.put("QUERY_RULE_ID", "1389");
		param.put("START_KEY", "1355656");
		param.put("END_KEY", "1895685");
		if (QUERY_PAGE == type) {
			param.put("CURRENT_PAGE", "1");
			param.put("PAGE_SIZE", "20");
			param.put("ORDERBY_COLUMN", "DU-JC");
			param.put("ORDER_DESC", "DU-JC");
		}

		// 请求数据
		Map<?, ?> obj = proxy.executeBySimpleMap("hbase01", Map.class, param);
		System.out.println(MetaWsDataUtil.toJSON(obj));
		System.exit(0);
	}
}
